#pragma once

static const char s_index_html[] =
    "<!doctype html><html><head><meta name=viewport content='width=device-width,initial-scale=1'><title>Stadia Dongle</title><style>body{font-family:Verdana,ui-sans-"
    "serif,sans-serif;margin:0;background:radial-gradient(circle at top left,#1e3a5f,#101827 42%,#070b12);color:#e5edf7}main{max-width:1100px;margin:auto;padding:22p"
    "x}.hero{padding:10px 4px 18px}.hero h1{margin:.1em 0;font-size:2.2rem}.hero p{color:#9fb2c8;margin:.2em 0}.grid{display:grid;grid-template-columns:repeat(auto-f"
    "it,minmax(260px,1fr));gap:14px}.card{background:rgba(15,23,42,.88);border:1px solid #31445f;border-radius:18px;padding:16px;box-shadow:0 10px 32px #0005}.wide{g"
    "rid-column:1/-1}.tiles{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.tile{background:#09111f;border:1px solid #263850;border-radius:14px;"
    "padding:12px}.k{color:#94a3b8;font-size:.78rem;text-transform:uppercase;letter-spacing:.06em}.v{font-size:1.1rem;margin-top:4px;word-break:break-word}button,inp"
    "ut,select{font:inherit;border-radius:11px;border:1px solid #49617c;background:#0a1322;color:#e5edf7;padding:10px;margin:4px}button{cursor:pointer;transition:.12"
    "s transform,.12s background}button:active{transform:scale(.97)}button.busy{background:#334155}button.ok{background:#14532d}button.danger{border-color:#ef4444;co"
    "lor:#fecaca}.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.err{color:#fecaca}.muted{color:#9fb2c8}.pill{display:inline-block;padding:5px 9px;borde"
    "r-radius:999px;background:#1e293b;margin:3px}.raw{font-family:monospace;color:#cbd5e1}.ctrl{background:#09111f;border:1px solid #263850;border-radius:14px;paddi"
    "ng:12px;margin:8px 0}.ctrltop{display:flex;justify-content:space-between;gap:10px;align-items:center}.ctrl.current{border-color:#22c55e;box-shadow:0 0 0 1px #22"
    "c55e55}.live{margin-top:10px;padding-top:10px;border-top:1px solid #263850}.badge{font-size:.78rem;color:#86efac;margin-left:6px}.dot{display:inline-block;width"
    ":18px;height:18px;border-radius:50%;vertical-align:middle;margin-right:8px;border:1px solid #94a3b8}.legend{list-style:none;padding:0;margin:0}.legend li{margin"
    ":7px 0}.white{background:#f8fafc}.blue{background:#2563eb}.cyan{background:#06b6d4}.yellow{background:#eab308}.green{background:#22c55e}.orange{background:#f973"
    "16}.purple{background:#a855f7}.red{background:#ef4444}.dim{background:#0f766e}</style></head><body><main><section class=hero><h1>Stadia Dongle</h1><p>BLE contro"
    "ller bridge, USB gamepad, setup portal, and utility HID.</p><p id=toast class=muted></p></section><div class=grid><section class='card wide'><h2>Status</h2><p i"
    "d=uierr class=err></p><div class=tiles><div class=tile><div class=k>State</div><div id=state class=v>Loading...</div></div><div class=tile><div class=k>Wi-Fi AP"
    "</div><div id=wifi class=v>Loading...</div></div><div class=tile><div class=k>Battery</div><div id=battery class=v>Loading...</div></div><div class=tile><div cl"
    "ass=k>Controller</div><div id=controller class=v>Loading...</div></div><div class=tile><div class=k>USB</div><div id=usb class=v>Loading...</div></div><div clas"
    "s=tile><div class=k>Wake</div><div id=wake class=v>Loading...</div></div><div class=tile><div class=k>Firmware</div><div id=fwver class=v>Loading...</div></div>"
    "</div><div class=row><button onclick='disableWeb(this)'>Disable Web UI</button><button onclick='reboot(this)'>Reboot</button></div></section><section class=card"
    "><h2>Input</h2><div id=pressed class=muted>Loading...</div><p class=raw id=raw></p><div class=tiles><div class=tile><div class=k>Left stick</div><div id=lst cla"
    "ss=v>-</div></div><div class=tile><div class=k>Right stick</div><div id=rst class=v>-</div></div><div class=tile><div class=k>Triggers</div><div id=trig class=v"
    ">-</div></div></div></section><section class=card><h2>Controllers</h2><div class=row><button onclick='pairStart(this)'>Start Pairing</button><button onclick='pa"
    "irStop(this)'>Stop Pairing</button><button class=danger onclick='forgetAll(this)'>Forget All</button></div><div id=controllers class=muted>Loading...</div></sec"
    "tion><section class=card><h2>Mouse Mode</h2><div class=tiles><div class=tile><div class=k>Enable / Disable</div><div class=v>Hold <b>Assistant + Capture</b> for"
    " 2 seconds</div></div><div class=tile><div class=k>Rumble feedback</div><div class=v>2 pulses = mouse ON / 3 pulses = mouse OFF</div></div></div><p class=muted>"
    "When mouse mode is active, the controller acts as a HID mouse. Controller input is disabled.</p><div class=tiles id=mousestatus><div class=tile><div class=k>Gam"
    "epad 0</div><div id=mm0 class=v>-</div></div><div class=tile><div class=k>Gamepad 1</div><div id=mm1 class=v>-</div></div></div></section><section class=card><h"
    "2>Extra Buttons</h2><label>Assistant short <select id=as></select></label><label>Assistant long <select id=al></select></label><label>Capture short <select id=c"
    "s></select></label><label>Capture long <select id=cl></select></label><label>Long press <input id=lp type=number min=300 max=5000 step=100 style='width:6em'> ms"
    "</label><label>Web UI timeout <input id=wt type=number min=15 max=1800 step=15 style='width:6em'> seconds</label><br><label><input id=ds type=checkbox>Disable A"
    "P when PC sleeps</label><button onclick='saveMap(this)'>Save mappings</button><p id=mapstatus class=muted></p></section><section class=card><h2>LED Legend</h2><"
    "ul class=legend><li><span class='dot white'></span>Booting: soft white pulse</li><li><span class='dot blue'></span>Scanning / no controller: dim blue heartbeat<"
    "/li><li><span class='dot blue'></span>Scanning + Wi-Fi AP on: blue-yellow alternating heartbeat</li><li><span class='dot green'></span>1 controller in gamepad m"
    "ode: green heartbeat</li><li><span class='dot green'></span>2 controllers in gamepad mode: faster green heartbeat</li><li><span class='dot purple'></span>PC sle"
    "eping: dim purple heartbeat</li><li><span class='dot orange'></span>Mouse mode active: orange heartbeat</li><li><span class='dot red'></span>Error: red pulsing<"
    "/li><li><span class='dot purple'></span>OTA update: purple/yellow animation</li><li><span class='dot white'></span>Remote wake sent: brief white flash</li></ul>"
    "</section><section class=card><h2>Firmware Update</h2><input id=fw type=file><button onclick='uploadFw(this)'>Upload</button><p id=update class=muted></p></sect"
    "ion></div></main><script>const $=id=>document.getElementById(id);let currentAddr='';const actions=['none','f13','f14','f15','f16','f17','f18','f19','f20','f21',"
    "'f22','f23','f24','printscreen','escape','tab','space','enter','backspace','insert','delete','home','end','page_up','page_down','arrow_up','arrow_down','arrow_l"
    "eft','arrow_right','volume_up','volume_down','mute','play_pause','next_track','prev_track','start_webui','remote_wake_only'];for(const id of ['as','al','cs','cl"
    "']){let s=$(id);actions.forEach(a=>s.add(new Option(a,a)));}async function api(p,o){let r=await fetch(p,o);let t=r.headers.get('content-type')||'';let v=t.inclu"
    "des('json')?await r.json():await r.text();if(!r.ok)throw new Error(typeof v==='string'?v:JSON.stringify(v));return v}function esc(s){return String(s==null?'':s)"
    ".replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'}[c]))}function setToast(s){$('toast').textContent=s;setTimeout(()=>{if($"
    "('toast').textContent==s)$('toast').textContent=''},2500)}async function clicked(btn,msg,fn){let old=btn?btn.textContent:'';if(btn){btn.disabled=true;btn.classL"
    "ist.add('busy');btn.textContent=msg||'Working...'}try{await fn();if(btn){btn.classList.remove('busy');btn.classList.add('ok');btn.textContent='Done'}setToast('D"
    "one')}catch(e){setToast('Failed: '+e.message);if(btn)btn.textContent='Failed'}finally{setTimeout(()=>{if(btn){btn.disabled=false;btn.classList.remove('busy','ok"
    "');btn.textContent=old}},900)}}function renderStatus(st){currentAddr=st.controller_address||'';$('state').textContent=String(st.state||'').split('_').join(' ');"
    "$('wifi').textContent=st.webui_active?('AP on / clients '+(st.webui_clients||0)+(st.webui_auto_off_seconds>0?' / auto-off '+st.webui_auto_off_seconds+'s':' / no"
    " timeout')):'AP off';$('battery').textContent=st.battery_percent==null?'Unavailable':st.battery_percent+'%';$('controller').innerHTML=st.ble_connected?esc(st.co"
    "ntroller_name||'Connected')+'<br><span class=muted>'+esc(currentAddr)+'</span>':'Not connected';$('usb').textContent=(st.usb_configured?'Configured':'Not config"
    "ured')+(st.usb_suspended?' / suspended':' / active');$('wake').textContent=st.usb_suspended?(st.usb_remote_wakeup_enabled?'Armed by host: controller can wake PC"
    "':'USB suspended, but host did not arm wake'):'Not armed: Windows has not suspended/armed this dongle. Enable wake on the HID Keyboard Device if available.';$('"
    "fwver').textContent=st.firmware_version+' / '+st.build_date;if(st.webui_auto_off_seconds>0)$('toast').textContent='Web UI auto-off in '+st.webui_auto_off_second"
    "s+'s unless a Wi-Fi client is connected'}function renderButtons(b){let names=(b.pressed||'').split(',').map(x=>x.trim()).filter(Boolean);$('pressed').innerHTML="
    "names.length?names.map(n=>'<span class=pill>'+esc(n)+'</span>').join(''):'No buttons pressed';$('raw').textContent=b.raw?'RAW '+b.raw:'';$('lst').textContent=b."
    "lx+','+b.ly;$('rst').textContent=b.rx+','+b.ry;$('trig').textContent='L '+b.lt+' / R '+b.rt}function renderControllers(c){let list=c.controllers||[];if(!list.le"
    "ngth){$('controllers').innerHTML='No stored controllers';return}$('controllers').innerHTML=list.map(x=>{let cur=!!x.connected;let batt=x.battery_percent==null?'"
    "battery unavailable':x.battery_percent+'%';let sub='USB gamepad '+x.usb_gamepad_index+' / slot '+x.slot_index+' / '+(x.ready?'ready':cur?'connecting':'stored')+"
    "' / '+batt;let names=(x.pressed||'').split(',').map(v=>v.trim()).filter(Boolean);let pills=names.length?names.map(n=>'<span class=pill>'+esc(n)+'</span>').join("
    "''):'<span class=muted>No buttons pressed</span>';let live=cur?'<div class=live><div class=k>Pressed</div>'+pills+'<div class=raw>'+(x.raw?'RAW '+esc(x.raw):'RA"
    "W unavailable')+'</div><div class=tiles><div class=tile><div class=k>Left stick</div><div class=v>'+x.lx+','+x.ly+'</div></div><div class=tile><div class=k>Righ"
    "t stick</div><div class=v>'+x.rx+','+x.ry+'</div></div><div class=tile><div class=k>Triggers</div><div class=v>L '+x.lt+' / R '+x.rt+'</div></div></div></div>':"
    "'';return '<div class=\"ctrl '+(cur?'current':'')+'\"><div class=ctrltop><div><b>'+esc(x.name||'Stadia Controller')+'</b>'+(cur?'<span class=badge>connected</sp"
    "an>':'')+'<br><span class=muted>'+esc(x.address)+'</span><br><span class=muted>'+esc(sub)+'</span></div><button class=danger data-address=\"'+esc(x.address)+'\""
    " onclick=\"forgetController(this,this.dataset.address)\">Forget</button></div>'+live+'</div>'}).join('');$('mm0').textContent=c.mouse_mode_0?'Active':'Inactive'"
    ";$('mm1').textContent=c.mouse_mode_1?'Active':'Inactive'}async function loadStatus(){try{$('uierr').textContent='';let st=await api('/api/status');renderStatus("
    "st);let b=await api('/api/buttons');renderButtons(b);let c=await api('/api/controllers');renderControllers(c)}catch(e){$('uierr').textContent='Status load faile"
    "d: '+e.message}}async function loadConfig(){try{let m=await api('/api/config/keymap');$('as').value=m.assistant_short;$('al').value=m.assistant_long;$('cs').val"
    "ue=m.capture_short;$('cl').value=m.capture_long;$('lp').value=m.long_press_ms||1000;$('wt').value=m.webui_timeout_seconds||120;$('ds').checked=m.disable_ap_on_s"
    "uspend!==false;$('mapstatus').textContent='Mappings loaded'}catch(e){$('mapstatus').textContent='Config load failed: '+e.message}}async function load(){await lo"
    "adStatus();await loadConfig()}async function pairStart(b){clicked(b,'Starting...',async()=>{await api('/api/pairing/start',{method:'POST'});await loadStatus()})"
    "}async function pairStop(b){clicked(b,'Stopping...',async()=>{await api('/api/pairing/stop',{method:'POST'});await loadStatus()})}async function forgetControlle"
    "r(b,a){if(confirm('Forget '+a+'?'))clicked(b,'Forgetting...',async()=>{await api('/api/controllers/forget',{method:'POST',headers:{'Content-Type':'application/x"
    "-www-form-urlencoded'},body:new URLSearchParams({address:a})});await loadStatus()})}async function forgetAll(b){if(confirm('Forget all bonded controllers?'))cli"
    "cked(b,'Forgetting...',async()=>{await api('/api/controllers/forget-all',{method:'POST'});await loadStatus()})}async function saveMap(b){clicked(b,'Saving...',a"
    "sync()=>{let body=new URLSearchParams({assistant_short:$('as').value,assistant_long:$('al').value,capture_short:$('cs').value,capture_long:$('cl').value,long_pr"
    "ess_ms:$('lp').value,webui_timeout_seconds:$('wt').value,disable_ap_on_suspend:$('ds').checked?'on':'off'});await api('/api/config/keymap',{method:'POST',header"
    "s:{'Content-Type':'application/x-www-form-urlencoded'},body});await loadConfig()})}async function disableWeb(b){clicked(b,'Disabling...',async()=>{await api('/a"
    "pi/webui/disable',{method:'POST'})})}async function reboot(b){clicked(b,'Rebooting...',async()=>{await api('/api/reboot',{method:'POST'})})}async function uploa"
    "dFw(b){let f=$('fw').files[0];if(!f)return;$('update').textContent='Uploading...';clicked(b,'Uploading...',async()=>{$('update').textContent=await api('/api/upd"
    "ate',{method:'POST',body:f})})}window.addEventListener('load',()=>{load();setInterval(loadStatus,3000)});</script></body></html>";

